before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
      - mips64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - '-s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.BuildDate={{.Date}} -X github.com/prometheus/common/version.Branch={{.Branch}} -X github.com/prometheus/common/version.BuildUser=goreleaser'

changelog:
  skip: true

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE.md
      - completions/*
      - manpages/*

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

brews:
  - repository:
      owner: nginxinc
      name: homebrew-tap
      token: '{{ .Env.NGINX_GITHUB_TOKEN }}'
    folder: Formula
    homepage: https://github.com/nginxinc/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
    extra_install: |-
      bash_completion.install "completions/nginx-prometheus-exporter.bash" => "nginx-prometheus-exporter"
      zsh_completion.install "completions/nginx-prometheus-exporter.zsh" => "_nginx-prometheus-exporter"
      man1.install "manpages/nginx-prometheus-exporter.1.gz"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

announce:
  slack:
    enabled: true
    channel: '#announcements'
    message_template: 'NGINX Prometheus Exporter {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'

milestones:
  - close: true

snapshot:
  name_template: 'edge'

snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    title: NGINX Prometheus Exporter
    summary: NGINX Prometheus Exporter for NGINX and NGINX Plus
    description: |
      NGINX Prometheus exporter fetches the metrics from NGINX or NGINX Plus,
      converts the metrics into appropriate Prometheus metrics types and finally exposes
      them via an HTTP server to be collected by Prometheus.
    grade: stable
    confinement: strict
    publish: true
    license: 'Apache-2.0'
    apps:
      nginx-prometheus-exporter:
        command: nginx-prometheus-exporter
        plugs: ["network", "network-bind"]
        completer: completions/nginx-prometheus-exporter.bash
    disable: "{{ if .IsSnapshot }}true{{ end }}"

nix:
  - repository:
      owner: nginxinc
      name: nur
      token: '{{ .Env.NGINX_GITHUB_TOKEN }}'
    homepage: https://github.com/nginxinc/nginx-prometheus-exporter
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: asl20
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
    extra_install: |-
      installManPage ./manpages/nginx-prometheus-exporter.1.gz
      installShellCompletion ./completions/*
