{
 "title": "NGINX",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(nginx_connections_waiting, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_connections_accepted{service=\"$service\"}[1m])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "increase(nginx_connections_handled{service=\"$service\"}[1m])",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_active{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_waiting{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Reading connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_reading{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Writing connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_connections_writing{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total HTTP Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_requests_total{service=\"$service\"}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}